parameters:
#    nomina.example.class: Nomina\NominaBundle\Example

services:
#    nomina.example:
#        class: %nomina.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
