<?php

namespace Nomina\NominaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * NominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NominaRepository extends EntityRepository
{
	public function getRegistrosSinProcesar()
	{
		$arr_nomina_sin_procesar = $this->createQueryBuilder('nom')
		->select('nom.id, nom.valor_devengado, nom.sueldo_base, nom.pension, nom.eps')
		->where( ' nom.valor_devengado is null and nom.pension is null ' )
		->getQuery()
		->getResult();
	
		return $arr_nomina_sin_procesar;
	}
	public function get_relacionados_usuario_nomina()
	{	
		$arr_nomina_relacionados = $this->createQueryBuilder('n')
			->select ('u.cedula, u.nombre, u.apellidos, n.sueldo_base, n.pension, n.eps, n.valor_devengado ')
			->innerJoin('NominaBundle:Usuario','u')
			->where( ' n.id = u.id_nomina ' )
            ->getQuery()
			->getResult();
		return $arr_nomina_relacionados;
	}

}
